### ISSUE TITLE
Password with ^ doesn work - needs to escape the special character?

### ISSUE THREAD

**Issue by thepiper18** [gazpachoking/trainaspower#18]
On my first try to install TrainAsPower, I noticed an error and checked the logs. My Stryd password contained the character '^' and this probably needed to be escaped in order for it to work. I just changed the password to a new one without any special characters and it worked perfectly. Maybe add this information on the readme file too, for other noobs like me? ;-) Thanks!

**Comment by gazpachoking** [comment]
Hmm. I have special characters in my password, and actually just reset it to something with a carat in, and it all seemed to work fine without any special escaping.
