### ISSUE TITLE
X_pace_adjust values in config do not adjust range

### ISSUE THREAD

**Issue by jamorris** [gazpachoking/trainaspower#24]
I changed all the pace adjust values in my config.yaml to `[-5, 5]` but the planned run on Final Surge  power values and range were the same as when the config values are `[0, 0]`. One run was an economy run and the other a perceived effort run (I have `number_of_workouts` set to 2).

**Comment by gazpachoking** [comment]
Ahh, yeah, this got broken when we switched to pulling the json workout from TaO. Sorry about that, I forgot to update the docs and add some warnings when it was still in the config. My current plan is to add back a global adjustment at the minimum. More granular control is a bit harder now, as we don't really get any info about each step other than for the warmup step. What sort of adjustments would be most useful to you (and everybody else?)

**Comment by jamorris** [comment]
A global adjustment sounds great. I have a hilly run and would like to be able to set everything to have a wider range. I don’t need granular control. Thanks for creating this tool, it’s an amazing project.

**Comment by gazpachoking** [comment]
Okay, I added a new 'power_adjust' to the config in latest version (0.7.3). It will now also warn if people still have the old X_pace_adjust options. 0bace157b1f133d98ffdfe6b58030b2979c54fa1

Thanks for the report!
