### ISSUE TITLE
3 step perceived effort runs not being calculated correctly

### ISSUE THREAD

**Issue by PatrickHastings** [gazpachoking/trainaspower#27]
When I am assigned Perceived Effort runs, they only have three steps: Stand, Run, Stand.
I think TrainAsPower is expecting there to be a warmup step as well as such the workout generated in Final Surge is: Stand, Warmup, Run.

![image](https://github.com/gazpachoking/trainaspower/assets/8702450/7acf43b9-b2b5-4da1-85a6-80b9d3ccf89e)

PR to follow

**Comment by gazpachoking** [comment]
Fixed by #28
